### ISSUE TITLE
Overly complex URLs

### ISSUE THREAD

**Issue by moimikey** [dakotahp/deparam#1]
This is an interesting one that I'm trying to fix on my own projects, where my deparam method is not correctly handling overly complex URLs like this:

```
http://test.com?utm_content=Email_2&c3=N7584.1920051SHOPKEEP.COM-115632261&c3creative=0&c3adid=%pc3dc=!;&c3size=%psz=!;#button
```

It looks absurd... but they exist... Should deparam to:

```
utm_content   Email_2
c3            N7584.1920051SHOPKEEP.COM-115632261
c3            A.B.C-D-E
c3creative    0
c3adid        %pc3dc=!;
c3size        %psz=!;#button
```

**Comment by dakotahp** [comment]
Blast from the past. Sorry for not responding _years_ ago.

I believe this is more a problem of poor encoding, specifically the `=` should at least be encoded as `%3D` so any equals in the URL conform to the key-val pattern for any parser. With just those fixed 

http://deparam.teardrop.co/#http://test.com?utm_content=Email_2&c3=N7584.1920051SHOPKEEP.COM-115632261&c3creative=0&c3adid=%25pc3dc%3D!;&c3size=%psz%3D!;#button

You've got duplicate keys using `c3` which also isn't valid.
